title: Xiaoli Chen
description: Personal blog and projects
url: "https://xchen101.github.io"

theme: minima

author:
  name: Xiaoli Chen

github_username: xchen101
linkedin_username: xiaolichen
instagram_username: 137ragnarok
bluesky_username: xiaolichen.bsky.social

collections:
  projects:
    output: true
    permalink: /projects/:name/
